PROPERTY_RECORDS = [
    {
        "property_id": "prop-bexar-001",
        "parcel_number": "BEX-1001-0001",
        "county": "Bexar",
        "city": "San Antonio",
        "region_key": "central_texas",
        "property_type": "single_family",
        "address_line1": "123 Mission Ridge Dr",
        "state": "TX",
        "postal_code": "78258",
        "latitude": 29.6407,
        "longitude": -98.4822,
        "bedrooms": 3.0,
        "bathrooms": 2.5,
        "building_area_sqft": 2150.0,
        "lot_size_acres": 0.19,
        "estimated_rent": 2450.0,
        "taxes_monthly": 525.0,
        "insurance_monthly": 140.0,
        "maintenance_monthly": 170.0,
        "hoa_monthly": 55.0,
        "vacancy_reserve_monthly": 120.0,
        "management_cost_monthly": 180.0,
        "zoning_code": "R-6",
        "land_use_code": "SFR",
        "parcel_resolution_confidence": 0.98,
        "source_name": "cad_bexar",
        "source_record_id": "cad-bexar-001",
        "source_observed_at": "2026-03-01T00:00:00Z",
        "source_fetched_at": "2026-03-05T00:00:00Z",
    },
    {
        "property_id": "prop-hays-002",
        "parcel_number": "HAY-2002-0002",
        "county": "Hays",
        "city": "San Marcos",
        "region_key": "central_texas",
        "property_type": "single_family",
        "address_line1": "48 Blanco Bend",
        "state": "TX",
        "postal_code": "78666",
        "latitude": 29.8821,
        "longitude": -97.9408,
        "bedrooms": 4.0,
        "bathrooms": 3.0,
        "building_area_sqft": 2480.0,
        "lot_size_acres": 0.24,
        "estimated_rent": 2650.0,
        "taxes_monthly": 560.0,
        "insurance_monthly": 150.0,
        "maintenance_monthly": 180.0,
        "hoa_monthly": 45.0,
        "vacancy_reserve_monthly": 130.0,
        "management_cost_monthly": 195.0,
        "zoning_code": "SF-2",
        "land_use_code": "SFR",
        "parcel_resolution_confidence": 0.96,
        "source_name": "cad_hays",
        "source_record_id": "cad-hays-002",
        "source_observed_at": "2026-03-01T00:00:00Z",
        "source_fetched_at": "2026-03-05T00:00:00Z",
    },
    {
        "property_id": "prop-travis-003",
        "parcel_number": "TRV-3003-0003",
        "county": "Travis",
        "city": "Austin",
        "region_key": "central_texas",
        "property_type": "single_family",
        "address_line1": "905 Barton Skyway",
        "state": "TX",
        "postal_code": "78704",
        "latitude": 30.2444,
        "longitude": -97.7801,
        "bedrooms": 3.0,
        "bathrooms": 2.0,
        "building_area_sqft": 1825.0,
        "lot_size_acres": 0.15,
        "estimated_rent": 3150.0,
        "taxes_monthly": 780.0,
        "insurance_monthly": 170.0,
        "maintenance_monthly": 190.0,
        "hoa_monthly": 0.0,
        "vacancy_reserve_monthly": 150.0,
        "management_cost_monthly": 225.0,
        "zoning_code": "SF-3",
        "land_use_code": "SFR",
        "parcel_resolution_confidence": 0.99,
        "source_name": "cad_travis",
        "source_record_id": "cad-travis-003",
        "source_observed_at": "2026-03-01T00:00:00Z",
        "source_fetched_at": "2026-03-05T00:00:00Z",
    },
]

LISTING_RECORDS = [
    {
        "listing_id": "listing-001",
        "property_id": "prop-bexar-001",
        "source_name": "demo_mls",
        "source_record_id": "mls-001",
        "listing_status": "active",
        "list_price": 365000.0,
        "listed_at": "2026-02-20",
        "removed_at": None,
        "days_on_market": 17,
        "bedrooms": 3.0,
        "bathrooms": 2.5,
        "building_area_sqft": 2150.0,
        "lot_size_acres": 0.19,
    },
    {
        "listing_id": "listing-002",
        "property_id": "prop-hays-002",
        "source_name": "demo_mls",
        "source_record_id": "mls-002",
        "listing_status": "active",
        "list_price": 425000.0,
        "listed_at": "2026-02-25",
        "removed_at": None,
        "days_on_market": 12,
        "bedrooms": 4.0,
        "bathrooms": 3.0,
        "building_area_sqft": 2480.0,
        "lot_size_acres": 0.24,
    },
    {
        "listing_id": "listing-003",
        "property_id": "prop-travis-003",
        "source_name": "demo_mls",
        "source_record_id": "mls-003",
        "listing_status": "active",
        "list_price": 625000.0,
        "listed_at": "2026-02-28",
        "removed_at": None,
        "days_on_market": 9,
        "bedrooms": 3.0,
        "bathrooms": 2.0,
        "building_area_sqft": 1825.0,
        "lot_size_acres": 0.15,
    },
]

TRANSACTION_RECORDS = [
    {
        "transaction_id": "txn-001",
        "property_id": "prop-bexar-001",
        "transaction_type": "sale",
        "recorded_date": "2023-06-01",
        "sale_price": 330000.0,
        "buyer_name": "Mission Ridge Holdings LLC",
        "seller_name": "Previous Owner A",
    },
    {
        "transaction_id": "txn-002",
        "property_id": "prop-hays-002",
        "transaction_type": "sale",
        "recorded_date": "2024-01-15",
        "sale_price": 360000.0,
        "buyer_name": "San Marcos Corridor LP",
        "seller_name": "Previous Owner B",
    },
    {
        "transaction_id": "txn-003",
        "property_id": "prop-travis-003",
        "transaction_type": "sale",
        "recorded_date": "2022-11-10",
        "sale_price": 540000.0,
        "buyer_name": "Austin Infill Ventures",
        "seller_name": "Previous Owner C",
    },
]

RISK_RECORDS = [
    {
        "property_id": "prop-bexar-001",
        "risk_layer": "flood",
        "risk_level": "moderate",
        "risk_score": 22.0,
        "effective_date": "2026-03-01",
        "source_name": "fema_nfhl",
        "source_record_id": "risk-bexar-flood",
    },
    {
        "property_id": "prop-bexar-001",
        "risk_layer": "wildfire",
        "risk_level": "low",
        "risk_score": 8.0,
        "effective_date": "2026-03-01",
        "source_name": "texas_wildfire_interface",
        "source_record_id": "risk-bexar-wildfire",
    },
    {
        "property_id": "prop-bexar-001",
        "risk_layer": "drought",
        "risk_level": "moderate",
        "risk_score": 35.0,
        "effective_date": "2026-03-01",
        "source_name": "usdm",
        "source_record_id": "risk-bexar-drought",
    },
    {
        "property_id": "prop-bexar-001",
        "risk_layer": "water_stress",
        "risk_level": "moderate",
        "risk_score": 40.0,
        "effective_date": "2026-03-01",
        "source_name": "texas_water_board",
        "source_record_id": "risk-bexar-water",
    },
    {
        "property_id": "prop-hays-002",
        "risk_layer": "flood",
        "risk_level": "low",
        "risk_score": 14.0,
        "effective_date": "2026-03-01",
        "source_name": "fema_nfhl",
        "source_record_id": "risk-hays-flood",
    },
    {
        "property_id": "prop-hays-002",
        "risk_layer": "wildfire",
        "risk_level": "low",
        "risk_score": 10.0,
        "effective_date": "2026-03-01",
        "source_name": "texas_wildfire_interface",
        "source_record_id": "risk-hays-wildfire",
    },
    {
        "property_id": "prop-hays-002",
        "risk_layer": "drought",
        "risk_level": "moderate",
        "risk_score": 31.0,
        "effective_date": "2026-03-01",
        "source_name": "usdm",
        "source_record_id": "risk-hays-drought",
    },
    {
        "property_id": "prop-hays-002",
        "risk_layer": "water_stress",
        "risk_level": "moderate",
        "risk_score": 34.0,
        "effective_date": "2026-03-01",
        "source_name": "texas_water_board",
        "source_record_id": "risk-hays-water",
    },
    {
        "property_id": "prop-travis-003",
        "risk_layer": "flood",
        "risk_level": "low",
        "risk_score": 12.0,
        "effective_date": "2026-03-01",
        "source_name": "fema_nfhl",
        "source_record_id": "risk-travis-flood",
    },
    {
        "property_id": "prop-travis-003",
        "risk_layer": "wildfire",
        "risk_level": "low",
        "risk_score": 6.0,
        "effective_date": "2026-03-01",
        "source_name": "texas_wildfire_interface",
        "source_record_id": "risk-travis-wildfire",
    },
    {
        "property_id": "prop-travis-003",
        "risk_layer": "drought",
        "risk_level": "moderate",
        "risk_score": 28.0,
        "effective_date": "2026-03-01",
        "source_name": "usdm",
        "source_record_id": "risk-travis-drought",
    },
    {
        "property_id": "prop-travis-003",
        "risk_layer": "water_stress",
        "risk_level": "moderate",
        "risk_score": 26.0,
        "effective_date": "2026-03-01",
        "source_name": "texas_water_board",
        "source_record_id": "risk-travis-water",
    },
]

RENTAL_MARKET_RECORDS = [
    {
        "region_key": "central_texas",
        "property_type": "single_family",
        "bedroom_count": 3,
        "effective_date": "2026-03-01",
        "median_rent": 2450.0,
        "vacancy_rate": 0.061,
        "growth_yoy": 0.045,
        "source_name": "demo_rental_market",
        "source_record_id": "rent-central-3br",
    },
    {
        "region_key": "central_texas",
        "property_type": "single_family",
        "bedroom_count": 4,
        "effective_date": "2026-03-01",
        "median_rent": 2650.0,
        "vacancy_rate": 0.058,
        "growth_yoy": 0.047,
        "source_name": "demo_rental_market",
        "source_record_id": "rent-central-4br",
    },
]

MARKET_FEATURE_RECORDS = [
    {
        "region_key": "central_texas",
        "feature_name": "appreciation_score",
        "feature_value": 72.0,
        "value_unit": "score",
        "effective_date": "2026-03-01",
        "source_name": "demo_market",
        "source_record_id": "market-appreciation",
    },
    {
        "region_key": "central_texas",
        "feature_name": "market_growth_score",
        "feature_value": 69.0,
        "value_unit": "score",
        "effective_date": "2026-03-01",
        "source_name": "demo_market",
        "source_record_id": "market-growth-score",
    },
    {
        "region_key": "central_texas",
        "feature_name": "liquidity_score",
        "feature_value": 64.0,
        "value_unit": "score",
        "effective_date": "2026-03-01",
        "source_name": "demo_market",
        "source_record_id": "market-liquidity-score",
    },
    {
        "region_key": "central_texas",
        "feature_name": "target_cap_rate",
        "feature_value": 0.0625,
        "value_unit": "ratio",
        "effective_date": "2026-03-01",
        "source_name": "demo_market",
        "source_record_id": "market-target-cap-rate",
    },
    {
        "region_key": "central_texas",
        "feature_name": "market_growth_rate",
        "feature_value": 0.041,
        "value_unit": "ratio",
        "effective_date": "2026-03-01",
        "source_name": "demo_market",
        "source_record_id": "market-growth-rate",
    },
]

LAND_FEATURE_RECORDS = [
    {
        "property_id": "prop-bexar-001",
        "feature_name": "utility_access_score",
        "feature_value": 82.0,
        "value_unit": "score",
        "effective_date": "2026-03-01",
        "source_name": "demo_land",
        "source_record_id": "land-bexar-utility",
    },
    {
        "property_id": "prop-hays-002",
        "feature_name": "utility_access_score",
        "feature_value": 78.0,
        "value_unit": "score",
        "effective_date": "2026-03-01",
        "source_name": "demo_land",
        "source_record_id": "land-hays-utility",
    },
    {
        "property_id": "prop-travis-003",
        "feature_name": "utility_access_score",
        "feature_value": 84.0,
        "value_unit": "score",
        "effective_date": "2026-03-01",
        "source_name": "demo_land",
        "source_record_id": "land-travis-utility",
    },
]
